name: Build Templates with Packer

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  list-templates:
    runs-on: [ self-hosted, Linux, X64, packer ]
    outputs:
      matrix: ${{ steps.get_dirs.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - name: Get packer directories
        id: get_dirs
        run: |
          DIRS=$(find packer/distros -name "*.pkr.hcl" -exec dirname {} \; | sort | uniq | jq -R -s -c 'split("\n")[:-1]')
          echo "matrix=$DIRS" >> $GITHUB_OUTPUT
  packer:
    needs: list-templates
    runs-on: [ self-hosted, Linux, X64, packer ]
    strategy:
      matrix:
        dir: ${{ fromJson(needs.list-templates.outputs.matrix) }}
      max-parallel: 2
    steps:
      - uses: actions/checkout@v4
      - name: Run Packer
        run: |
          source $HOME/.env
          cd ${{ matrix.dir }}
          packer init .
          packer validate .
          packer build .
